import { UserProfile } from '@/types/user';
import { Trip, Vehicle } from '@/types/trip';
import { TripRequest } from '@/types/request';
import { Connection } from '@/types/connection';
import { Message, ConversationSummary } from '@/types/message';

export const mockCurrentUser: UserProfile = {
  id: 'usr_me_1',
  full_name: 'Piyush Sharma',
  email: 'piyush@example.com',
  phone: '+91 98765 43210',
  bio: 'Software engineer traveling frequently between Pune and Hyderabad. Friendly, punctual, non-smoker.',
  role: 'both',
  verification_status: 'verified',
  rating: 4.9,
  rating_count: 18,
  total_trips: 12,
  created_at: '2025-08-10T10:00:00Z',
};

export const mockDrivers: UserProfile[] = [
  {
    id: 'usr_driver_1',
    full_name: 'Vikram Joshi',
    email: 'vikram.j@example.com',
    phone: '+91 98123 45678',
    bio: 'Frequent intercity commuter. Regular trips from Pune to Hyderabad on weekends. Safe driver with 10+ years experience.',
    role: 'driver',
    verification_status: 'verified',
    rating: 4.95,
    rating_count: 42,
    total_trips: 38,
    created_at: '2025-01-15T09:00:00Z',
  },
  {
    id: 'usr_driver_2',
    full_name: 'Ananya Deshmukh',
    email: 'ananya.d@example.com',
    phone: '+91 98234 56789',
    bio: 'Healthcare professional heading to Solapur twice a month. Quiet and comfortable rides with pleasant music.',
    role: 'driver',
    verification_status: 'verified',
    rating: 4.88,
    rating_count: 24,
    total_trips: 19,
    created_at: '2025-03-22T11:30:00Z',
  },
  {
    id: 'usr_driver_3',
    full_name: 'Rajesh Nair',
    email: 'rajesh.nair@example.com',
    phone: '+91 98345 67890',
    bio: 'Tech consultant commuting between Mumbai and Pune. Eco-friendly electric vehicle.',
    role: 'driver',
    verification_status: 'unverified',
    rating: 4.7,
    rating_count: 8,
    total_trips: 6,
    created_at: '2025-07-04T14:15:00Z',
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: 'veh_1',
    owner_id: 'usr_driver_1',
    vehicle_type: 'suv',
    vehicle_model: 'Hyundai Creta (White)',
    registration_number: 'MH 12 AB 9988',
    seats: 4,
    color: 'Polar White',
    created_at: '2025-01-16T10:00:00Z',
  },
  {
    id: 'veh_2',
    owner_id: 'usr_driver_2',
    vehicle_type: 'sedan',
    vehicle_model: 'Honda City (Grey)',
    registration_number: 'MH 14 CD 4521',
    seats: 4,
    color: 'Modern Steel',
    created_at: '2025-03-23T12:00:00Z',
  },
  {
    id: 'veh_3',
    owner_id: 'usr_driver_3',
    vehicle_type: 'ev',
    vehicle_model: 'Tata Nexon EV (Teal)',
    registration_number: 'MH 02 EF 7812',
    seats: 4,
    color: 'Signature Teal',
    created_at: '2025-07-05T15:00:00Z',
  },
];

export const mockTrips: Trip[] = [
  {
    id: 'trip_101',
    driver_id: 'usr_driver_1',
    vehicle_id: 'veh_1',
    origin_name: 'Pune (Swargate / Hadapsar)',
    destination_name: 'Hyderabad (Gachibowli / Hitec City)',
    departure_date: '2026-09-25',
    departure_time: '08:00',
    available_seats: 2,
    total_seats: 3,
    contribution_mode: 'discuss',
    suggested_contribution: 650,
    notes: 'Starting early morning from Hadapsar. Spacious boot space for 1 bag per person. AC on throughout. Mutual contribution to cover toll & fuel.',
    preferences: {
      luggage_allowed: true,
      music_preference: 'Acoustic / Indie Pop',
      smoking_allowed: false,
      pets_allowed: false,
    },
    status: 'published',
    is_featured: true,
    is_detailed_route_unlocked: false,
    created_at: '2026-09-18T10:30:00Z',
    driver: mockDrivers[0],
    vehicle: mockVehicles[0],
  },
  {
    id: 'trip_102',
    driver_id: 'usr_driver_2',
    vehicle_id: 'veh_2',
    origin_name: 'Pune (Kothrud)',
    destination_name: 'Solapur (Old Bus Stand)',
    departure_date: '2026-09-25',
    departure_time: '07:30',
    available_seats: 3,
    total_seats: 3,
    contribution_mode: 'suggested',
    suggested_contribution: 400,
    notes: 'Direct expressway route with a quick 15 min breakfast stop near Indapur. Clean car and smooth driving.',
    preferences: {
      luggage_allowed: true,
      music_preference: 'Classical / Instrumental',
      smoking_allowed: false,
      pets_allowed: true,
    },
    status: 'published',
    is_featured: false,
    is_detailed_route_unlocked: true,
    created_at: '2026-09-19T08:00:00Z',
    driver: mockDrivers[1],
    vehicle: mockVehicles[1],
  },
  {
    id: 'trip_103',
    driver_id: 'usr_driver_3',
    vehicle_id: 'veh_3',
    origin_name: 'Mumbai (Dadar / Chembur)',
    destination_name: 'Pune (Baner / Wakad)',
    departure_date: '2026-09-26',
    departure_time: '09:00',
    available_seats: 1,
    total_seats: 3,
    contribution_mode: 'discuss',
    suggested_contribution: 350,
    notes: 'Via Mumbai-Pune Expressway. Whisper quiet EV ride. Charging stop at Talegaon if needed.',
    preferences: {
      luggage_allowed: true,
      music_preference: 'Podcasts & News',
      smoking_allowed: false,
      pets_allowed: false,
    },
    status: 'published',
    is_featured: false,
    is_detailed_route_unlocked: false,
    created_at: '2026-09-19T14:45:00Z',
    driver: mockDrivers[2],
    vehicle: mockVehicles[2],
  },
  {
    id: 'trip_104',
    driver_id: 'usr_me_1',
    vehicle_id: 'veh_1',
    origin_name: 'Pune (Viman Nagar)',
    destination_name: 'Nagpur (Sitabuldi)',
    departure_date: '2026-09-30',
    departure_time: '06:00',
    available_seats: 2,
    total_seats: 3,
    contribution_mode: 'discuss',
    suggested_contribution: 950,
    notes: 'Samruddhi Mahamarg route. Fast and scenic journey. Happy to coordinate pickup along Nagar Road.',
    preferences: {
      luggage_allowed: true,
      smoking_allowed: false,
      pets_allowed: false,
    },
    status: 'published',
    is_featured: false,
    is_detailed_route_unlocked: false,
    created_at: '2026-09-19T16:00:00Z',
    driver: mockCurrentUser,
    vehicle: mockVehicles[0],
  },
];

export const mockRequests: TripRequest[] = [
  {
    id: 'req_201',
    trip_id: 'trip_101',
    passenger_id: 'usr_me_1',
    seats_requested: 1,
    message: 'Hi Vikram, heading to Hyderabad for a client sprint. Have 1 small trolley bag. Can meet you at Hadapsar Magarpatta junction.',
    status: 'accepted',
    created_at: '2026-09-19T11:20:00Z',
    passenger: mockCurrentUser,
    trip: mockTrips[0],
  },
  {
    id: 'req_202',
    trip_id: 'trip_102',
    passenger_id: 'usr_me_1',
    seats_requested: 1,
    message: 'Hello Ananya, need a ride to Solapur on Friday morning. Please let me know if seat is still free.',
    status: 'pending',
    created_at: '2026-09-20T09:15:00Z',
    passenger: mockCurrentUser,
    trip: mockTrips[1],
  },
  {
    id: 'req_203',
    trip_id: 'trip_104',
    passenger_id: 'usr_driver_3',
    seats_requested: 1,
    message: 'Hi Piyush, need to visit family in Nagpur. Flexible on timing. Glad to share fuel contribution.',
    status: 'pending',
    created_at: '2026-09-20T10:45:00Z',
    passenger: mockDrivers[2],
    trip: mockTrips[3],
  },
];

export const mockConnections: Connection[] = [
  {
    id: 'conn_301',
    trip_id: 'trip_101',
    driver_id: 'usr_driver_1',
    passenger_id: 'usr_me_1',
    request_id: 'req_201',
    status: 'active',
    pickup_notes: 'Pickup: Magarpatta South Gate at 08:15 AM. Drop: Gachibowli Circle.',
    agreed_contribution: 'Discussed & agreed: ₹650 towards toll and fuel share',
    created_at: '2026-09-19T14:00:00Z',
    driver: mockDrivers[0],
    passenger: mockCurrentUser,
    trip: mockTrips[0],
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg_1',
    connection_id: 'conn_301',
    sender_id: 'usr_me_1',
    receiver_id: 'usr_driver_1',
    message: 'Hi Vikram! Thanks for accepting the seat request. Looking forward to the trip.',
    created_at: '2026-09-19T14:05:00Z',
  },
  {
    id: 'msg_2',
    connection_id: 'conn_301',
    sender_id: 'usr_driver_1',
    receiver_id: 'usr_me_1',
    message: 'Hey Piyush! Most welcome. Magarpatta South Gate works perfectly for me. Does 8:15 AM sound good?',
    created_at: '2026-09-19T14:10:00Z',
  },
  {
    id: 'msg_3',
    connection_id: 'conn_301',
    sender_id: 'usr_me_1',
    receiver_id: 'usr_driver_1',
    message: '8:15 AM is ideal. I will be ready right outside the main gate. How would you like to split the contribution?',
    created_at: '2026-09-19T14:15:00Z',
  },
  {
    id: 'msg_4',
    connection_id: 'conn_301',
    sender_id: 'usr_driver_1',
    receiver_id: 'usr_me_1',
    message: '₹650 via UPI during our rest stop at Solapur bypass is fine with me. See you on Friday!',
    created_at: '2026-09-19T14:20:00Z',
  },
];

export const mockConversations: ConversationSummary[] = [
  {
    connection_id: 'conn_301',
    other_user: mockDrivers[0],
    trip_route: 'Pune → Hyderabad',
    trip_date: '25 Sep, 08:00 AM',
    last_message: mockMessages[3],
    unread_count: 0,
  },
];
